apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  selector:
    app: hello
    tier: backend
    track: stable
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000