name: Docker CI/CD for server

on:
  push:
    branches: ["main", "tam-k8s-docker-CI-CD" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-docker:

    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - uses: actions/checkout@v3
    - name: Build the backend Docker image
      run: |
        docker build -t backend-golang --target program .
        docker build -t mysql-db --target db .
      working-directory: ./backend
    
    # - name: test
    #   run: pwd

    - name: Run backend docker to test
      run : |
        docker-compose up -d
      working-directory: ./backend

    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install library 
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run test case
      run : |
        python3 -m unittest tests.test_user
      working-directory: ./test_case


    - name: Stop docker compose
      run : |
        docker compose stop
  